### ISSUE TITLE
Access player

### ISSUE THREAD

**Issue by MentalIllness** [Apestein/nextflix#13]
Basically I want to access the user membership via a client side, because I am making some modifications ( to be more specific from modal-card.tsx ). Is this possible and do you have any recommendations? I was thinking about hosting API but not sure.

**Comment by Apestein** [comment]
> Basically I want to access the user membership via a client side, because I am making some modifications ( to be more specific from modal-card.tsx ). Is this possible and do you have any recommendations? I was thinking about hosting API but not sure.

Just fetch from server component and pass in as props to [modal.tsx -> modal-card.tsx](https://github.com/Apestein/nextflix/blob/main/src/app/(main)/%40modal/(.)show/%5Bid%5D/page.tsx).

**Comment by marso006** [comment]
Thank you I did it and it works. Nice project btw
